"""
MITRE ATT&CK Coverage API.

GET /api/v1/mitre/coverage  — ATT&CK Navigator-compatible heatmap JSON.
GET /api/v1/mitre/summary   — human-readable technique counts and tactic breakdown.

Coverage is calculated from all Incident records that have mitre_techniques populated.
The Navigator JSON can be pasted directly into https://mitre-attack.github.io/attack-navigator/
to visualize detection coverage as a shareable heatmap.
"""

import logging
from collections import Counter, defaultdict
from datetime import datetime, timezone
from typing import Any, Dict, List

from fastapi import APIRouter, Depends, HTTPException, Security
from fastapi import status as http_status
from fastapi.security import APIKeyHeader
from sqlalchemy.orm import Session

from app.database import get_db
from app.config import settings
from app import models

logger = logging.getLogger(__name__)
router = APIRouter()

api_key_header = APIKeyHeader(name="x-api-key", auto_error=False)


def verify_api_key(x_api_key: str = Security(api_key_header)) -> str:
    if not x_api_key or x_api_key != settings.API_KEY:
        raise HTTPException(status_code=http_status.HTTP_401_UNAUTHORIZED, detail="Invalid API key")
    return x_api_key


# MITRE tactic → techniques mapping (subset relevant to TrustSOC detection patterns)
_TACTIC_ORDER = [
    "reconnaissance", "resource-development", "initial-access", "execution",
    "persistence", "privilege-escalation", "defense-evasion", "credential-access",
    "discovery", "lateral-movement", "collection", "command-and-control",
    "exfiltration", "impact",
]

# Technique → tactic lookup (built from what TrustSOC correlation engine maps)
_TECHNIQUE_TO_TACTIC = {
    "T1110":     "credential-access",
    "T1110.001": "credential-access",
    "T1110.003": "credential-access",
    "T1021":     "lateral-movement",
    "T1021.001": "lateral-movement",
    "T1021.002": "lateral-movement",
    "T1078":     "privilege-escalation",
    "T1136":     "persistence",
    "T1136.001": "persistence",
    "T1059":     "execution",
    "T1059.001": "execution",
    "T1003":     "credential-access",
    "T1003.001": "credential-access",
    "T1486":     "impact",
    "T1041":     "exfiltration",
    "T1566":     "initial-access",
    "T1566.001": "initial-access",
}


def _get_technique_counts(db: Session) -> Counter:
    """Count how many incidents detected each MITRE technique."""
    counts: Counter = Counter()
    incidents = db.query(models.Incident).filter(
        models.Incident.mitre_techniques.isnot(None)
    ).all()
    for inc in incidents:
        techs = inc.mitre_techniques or []
        if isinstance(techs, list):
            for t in techs:
                if t:
                    counts[t.upper()] += 1
    return counts


# ---------------------------------------------------------------------------
# GET /coverage — ATT&CK Navigator JSON
# ---------------------------------------------------------------------------
@router.get("/coverage", summary="MITRE ATT&CK Navigator-compatible coverage heatmap")
def get_coverage(
    db: Session = Depends(get_db),
    api_key: str = Depends(verify_api_key),
):
    """
    Returns JSON compatible with the MITRE ATT&CK Navigator layer format.
    Paste the response into https://mitre-attack.github.io/attack-navigator/
    to see your detection coverage as a color-coded heatmap.

    Score = number of incidents that triggered each technique.
    Color gradient: 0 = white (no coverage), higher = darker blue.
    """
    counts = _get_technique_counts(db)

    techniques: List[Dict[str, Any]] = []
    for tech_id, count in counts.items():
        techniques.append({
            "techniqueID": tech_id,
            "score": count,
            "color": "",
            "comment": f"Detected in {count} incident(s)",
            "enabled": True,
            "metadata": [],
            "showSubtechniques": True,
        })

    # Also include zero-score entries for techniques TrustSOC can detect
    # (shows "monitored but not triggered" in Navigator)
    detected_ids = set(counts.keys())
    for tech_id in _TECHNIQUE_TO_TACTIC:
        upper = tech_id.upper()
        if upper not in detected_ids:
            techniques.append({
                "techniqueID": upper,
                "score": 0,
                "color": "#c6def1",
                "comment": "TrustSOC monitors for this technique",
                "enabled": True,
                "metadata": [],
                "showSubtechniques": False,
            })

    return {
        "name": "TrustSOC Detection Coverage",
        "versions": {"attack": "14", "navigator": "4.9", "layer": "4.5"},
        "domain": "enterprise-attack",
        "description": f"Auto-generated by TrustSOC. Last updated: {datetime.now(timezone.utc).isoformat()}",
        "filters": {"platforms": ["Windows", "Linux", "macOS", "Network"]},
        "sorting": 0,
        "layout": {"layout": "side", "showID": True, "showName": True},
        "hideDisabled": False,
        "techniques": techniques,
        "gradient": {
            "colors": ["#ffffff", "#1f77b4"],
            "minValue": 0,
            "maxValue": max(counts.values()) if counts else 1,
        },
        "legendItems": [
            {"label": "No detections", "color": "#ffffff"},
            {"label": "Monitored", "color": "#c6def1"},
            {"label": "Detected", "color": "#1f77b4"},
        ],
        "metadata": [],
        "showTacticRowBackground": True,
        "tacticRowBackground": "#dddddd",
    }


# ---------------------------------------------------------------------------
# GET /summary — human-readable breakdown
# ---------------------------------------------------------------------------
@router.get("/summary", summary="MITRE ATT&CK coverage summary")
def get_summary(
    db: Session = Depends(get_db),
    api_key: str = Depends(verify_api_key),
):
    counts = _get_technique_counts(db)

    by_tactic: Dict[str, List[Dict]] = defaultdict(list)
    for tech_id, count in counts.items():
        tactic = _TECHNIQUE_TO_TACTIC.get(tech_id, "unknown")
        by_tactic[tactic].append({"technique": tech_id, "incident_count": count})

    # Sort each tactic's list by count desc
    for tactic in by_tactic:
        by_tactic[tactic].sort(key=lambda x: x["incident_count"], reverse=True)

    total_incidents = db.query(models.Incident).count()

    return {
        "total_techniques_detected": len(counts),
        "total_techniques_monitored": len(_TECHNIQUE_TO_TACTIC),
        "total_incidents": total_incidents,
        "coverage_percent": round(len(counts) / len(_TECHNIQUE_TO_TACTIC) * 100, 1) if _TECHNIQUE_TO_TACTIC else 0,
        "by_tactic": dict(by_tactic),
        "top_techniques": counts.most_common(10),
        "navigator_url": "https://mitre-attack.github.io/attack-navigator/",
        "navigator_hint": "GET /api/v1/mitre/coverage → paste JSON into Navigator",
    }
