"""initial_schema

Revision ID: 58a01322819a
Revises: 
Create Date: 2026-03-31 23:18:50.318827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58a01322819a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actions', 'executed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('actions', 'rollback_deadline',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index('idx_actions_alert', table_name='actions')
    op.drop_index('idx_actions_incident', table_name='actions')
    op.create_index(op.f('ix_actions_alert_id'), 'actions', ['alert_id'], unique=False)
    op.create_index(op.f('ix_actions_incident_id'), 'actions', ['incident_id'], unique=False)
    op.alter_column('alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('alerts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('alerts_external_id_key', 'alerts', type_='unique')
    op.drop_index('idx_alerts_created', table_name='alerts')
    op.drop_index('idx_alerts_incident', table_name='alerts')
    op.drop_index('idx_alerts_risk', table_name='alerts')
    op.drop_index('idx_alerts_status', table_name='alerts')
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_external_id'), 'alerts', ['external_id'], unique=True)
    op.create_index(op.f('ix_alerts_incident_id'), 'alerts', ['incident_id'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_foreign_key(None, 'alerts', 'incidents', ['incident_id'], ['id'])
    op.alter_column('assets', 'last_seen',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('assets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('assets_hostname_key', 'assets', type_='unique')
    op.drop_index('idx_assets_hostname', table_name='assets')
    op.drop_index('idx_assets_ip', table_name='assets')
    op.create_index(op.f('ix_assets_hostname'), 'assets', ['hostname'], unique=True)
    op.create_index(op.f('ix_assets_ip_address'), 'assets', ['ip_address'], unique=False)
    op.add_column('enrichments', sa.Column('cost_usd', sa.DECIMAL(precision=10, scale=6), nullable=True))
    op.add_column('enrichments', sa.Column('cached', sa.Boolean(), nullable=True))
    op.add_column('enrichments', sa.Column('api_calls_made', sa.Integer(), nullable=True))
    op.alter_column('enrichments', 'alert_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('enrichments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_enrichments_alert', table_name='enrichments')
    op.create_index(op.f('ix_enrichments_alert_id'), 'enrichments', ['alert_id'], unique=False)
    op.drop_constraint('enrichments_alert_id_fkey', 'enrichments', type_='foreignkey')
    op.create_foreign_key(None, 'enrichments', 'alerts', ['alert_id'], ['id'])
    op.alter_column('evidence', 'collected_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_evidence_alert', table_name='evidence')
    op.drop_index('idx_evidence_incident', table_name='evidence')
    op.create_index(op.f('ix_evidence_alert_id'), 'evidence', ['alert_id'], unique=False)
    op.create_index(op.f('ix_evidence_incident_id'), 'evidence', ['incident_id'], unique=False)
    op.drop_constraint('evidence_incident_id_fkey', 'evidence', type_='foreignkey')
    op.drop_constraint('evidence_alert_id_fkey', 'evidence', type_='foreignkey')
    op.create_foreign_key(None, 'evidence', 'alerts', ['alert_id'], ['id'])
    op.create_foreign_key(None, 'evidence', 'incidents', ['incident_id'], ['id'])
    op.alter_column('feedback', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_feedback_alert', table_name='feedback')
    op.create_index(op.f('ix_feedback_alert_id'), 'feedback', ['alert_id'], unique=False)
    op.create_index(op.f('ix_feedback_incident_id'), 'feedback', ['incident_id'], unique=False)
    op.alter_column('incidents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('incidents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('incidents', 'closed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index('idx_incidents_created', table_name='incidents')
    op.drop_index('idx_incidents_severity', table_name='incidents')
    op.drop_index('idx_incidents_status', table_name='incidents')
    op.create_index(op.f('ix_incidents_created_at'), 'incidents', ['created_at'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.alter_column('policy_executions', 'executed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_policy_executions_alert_id'), 'policy_executions', ['alert_id'], unique=False)
    op.alter_column('suppressions', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('suppressions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users_context', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users_context', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_users_username', table_name='users_context')
    op.drop_constraint('users_context_username_key', 'users_context', type_='unique')
    op.create_index(op.f('ix_users_context_username'), 'users_context', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_context_username'), table_name='users_context')
    op.create_unique_constraint('users_context_username_key', 'users_context', ['username'])
    op.create_index('idx_users_username', 'users_context', ['username'], unique=False)
    op.alter_column('users_context', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users_context', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('suppressions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('suppressions', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('ix_policy_executions_alert_id'), table_name='policy_executions')
    op.alter_column('policy_executions', 'executed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_created_at'), table_name='incidents')
    op.create_index('idx_incidents_status', 'incidents', ['status'], unique=False)
    op.create_index('idx_incidents_severity', 'incidents', ['severity'], unique=False)
    op.create_index('idx_incidents_created', 'incidents', [sa.text('created_at DESC')], unique=False)
    op.alter_column('incidents', 'closed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('incidents', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('incidents', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_feedback_incident_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_alert_id'), table_name='feedback')
    op.create_index('idx_feedback_alert', 'feedback', ['alert_id'], unique=False)
    op.alter_column('feedback', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'evidence', type_='foreignkey')
    op.drop_constraint(None, 'evidence', type_='foreignkey')
    op.create_foreign_key('evidence_alert_id_fkey', 'evidence', 'alerts', ['alert_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('evidence_incident_id_fkey', 'evidence', 'incidents', ['incident_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_evidence_incident_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_alert_id'), table_name='evidence')
    op.create_index('idx_evidence_incident', 'evidence', ['incident_id'], unique=False)
    op.create_index('idx_evidence_alert', 'evidence', ['alert_id'], unique=False)
    op.alter_column('evidence', 'collected_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'enrichments', type_='foreignkey')
    op.create_foreign_key('enrichments_alert_id_fkey', 'enrichments', 'alerts', ['alert_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_enrichments_alert_id'), table_name='enrichments')
    op.create_index('idx_enrichments_alert', 'enrichments', ['alert_id'], unique=False)
    op.alter_column('enrichments', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('enrichments', 'alert_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('enrichments', 'api_calls_made')
    op.drop_column('enrichments', 'cached')
    op.drop_column('enrichments', 'cost_usd')
    op.drop_index(op.f('ix_assets_ip_address'), table_name='assets')
    op.drop_index(op.f('ix_assets_hostname'), table_name='assets')
    op.create_index('idx_assets_ip', 'assets', ['ip_address'], unique=False)
    op.create_index('idx_assets_hostname', 'assets', ['hostname'], unique=False)
    op.create_unique_constraint('assets_hostname_key', 'assets', ['hostname'])
    op.alter_column('assets', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('assets', 'last_seen',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_incident_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_external_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.create_index('idx_alerts_status', 'alerts', ['status'], unique=False)
    op.create_index('idx_alerts_risk', 'alerts', [sa.text('risk_score DESC')], unique=False)
    op.create_index('idx_alerts_incident', 'alerts', ['incident_id'], unique=False)
    op.create_index('idx_alerts_created', 'alerts', [sa.text('created_at DESC')], unique=False)
    op.create_unique_constraint('alerts_external_id_key', 'alerts', ['external_id'])
    op.alter_column('alerts', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('alerts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_actions_incident_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_alert_id'), table_name='actions')
    op.create_index('idx_actions_incident', 'actions', ['incident_id'], unique=False)
    op.create_index('idx_actions_alert', 'actions', ['alert_id'], unique=False)
    op.alter_column('actions', 'rollback_deadline',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('actions', 'executed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
